add secret-manager module with example usage
Selleo/terraform-aws-iam pull request #1
Opened 2021-12-14 19:19 UTC by mateuszwu

2021-12-16 12:03 UTC, qbart requested changes
Few changes needed, I might have copied something wrong, make sure naming is correct

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/variables.tf
> +variable "full_access_users" {
let's rename `full_access_users` to `write`, giving  both`read & write` permissions means that user has full access

2021-12-16 12:03 UTC, qbart commented on examples/secret-manager/versions.tf
> +  default_tags {
we can skip tags for examples

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/variables.tf
> +variable "secrets" {
we need to introduce new variable `name_prefix` that will be prepended to resources

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  users      = setunion(var.read_access_users, var.full_access_users)
limit read to only read

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  name   = "read_policy"
`name = "${var.name_prefix}-secret-read"`

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +resource "aws_iam_policy" "read_policy" {
it's a policy, not need to call it `read_policy`, it should give a meaning of what it does i.e. `read_secret`

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +data "aws_iam_policy_document" "write_policy" {
`write_policy` -> `write_secret`

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +data "aws_iam_policy_document" "read_policy" {
```suggestion
data "aws_iam_policy_document" "read_secret" {
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +      "secretsmanager:ListSecretVersionIds",
```suggestion
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +      "secretsmanager:ListSecretVersionIds",
this is read permission

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +    ]
```suggestion
      "secretsmanager:ListSecretVersionIds",
    ]
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  name   = "read_policy"
IAM names are globally unique, we need this ☝️

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +resource "aws_iam_policy_attachment" "read_attachment" {
```suggestion
resource "aws_iam_policy_attachment" "secret_read" {
```
attachment is already in resource name

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  name       = "read_attachment"
```suggestion
  name       = "${var.prefix_name}-secret-read"
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +resource "aws_iam_policy" "write_policy" {
fix name (similar to read approach)

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  name   = "write_policy"
```suggestion
  name   = "${var.prefix_name}-secret-write"
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +  name       = "write_attachment"
```suggestion
  name       = "${var.prefix_name}-secret-write"
```

2021-12-16 12:03 UTC, qbart commented on modules/secret-manager/main.tf
> +resource "aws_iam_policy_attachment" "write_attachment" {
fix resource naming

2021-12-27 11:13 UTC, qbart commented
@mateuszwu I tried to use it and it fails in the following context (when one of the read/write users field is empty):
```
module "aws_iam_secret_manager_policy" {
  source      = "../../modules/secret-manager"
  name_prefix = "bart-aws-iam-secret-manager"
  secrets     = [aws_secretsmanager_secret.secret_no_1.arn]
  read_users  = []
  write_users = [aws_iam_user.full_access_user.name]
}

module "aws_iam_secret_manager_policy2" {
  source      = "../../modules/secret-manager"
  name_prefix = "bart-aws-iam-secret-manager2"
  secrets     = [aws_secretsmanager_secret.secret_no_2.arn]
  read_users  = [aws_iam_user.read_only_user.name]
  write_users = []
}
```

2021-12-27 19:17 UTC, mateuszwu commented
> @mateuszwu I tried to use it and it fails in the following context (when one of the read/write users field is empty):
> 
> ```
> module "aws_iam_secret_manager_policy" {
>   source      = "../../modules/secret-manager"
>   name_prefix = "bart-aws-iam-secret-manager"
>   secrets     = [aws_secretsmanager_secret.secret_no_1.arn]
>   read_users  = []
>   write_users = [aws_iam_user.full_access_user.name]
> }
> 
> module "aws_iam_secret_manager_policy2" {
>   source      = "../../modules/secret-manager"
>   name_prefix = "bart-aws-iam-secret-manager2"
>   secrets     = [aws_secretsmanager_secret.secret_no_2.arn]
>   read_users  = [aws_iam_user.read_only_user.name]
>   write_users = []
> }
> ```

@qbart everything should be working now.

2021-12-27 22:59 UTC, qbart requested changes
Final touches and we can merge

2021-12-27 22:59 UTC, qbart commented on examples/secret-manager/main.tf
> +output "IAM_user1_id" {
as a final touch, let's fix upper case style to lower case

2021-12-28 12:23 UTC, qbart approved these changes

2021-12-28 12:38 UTC, merged