add cloudfront module with example usage
Selleo/terraform-aws-iam pull request #3
Opened 2021-12-15 21:02 UTC by mateuszwu

2021-12-16 12:24 UTC, qbart requested changes
small changes

2021-12-16 12:24 UTC, qbart commented on examples/cloudfront/main.tf
> +resource "aws_cloudfront_distribution" "example_cloudfront" {
rather than creating example from scratch, use our modules

2021-12-16 12:24 UTC, qbart commented on modules/cloudfront/main.tf
> +resource "aws_iam_policy" "this" {
missing `name` attribute

2021-12-16 12:24 UTC, qbart commented on modules/cloudfront/main.tf
> +  name       = "cloudfront-invalidation-policy"
```suggestion
  name       = "${var.name_prefix}-cdn-invalidation"
```

2021-12-28 16:55 UTC, qbart commented on modules/cloudfront/variables.tf
> +  description = "Prefix that will be prepended to resources names"
```suggestion
  description = "Prefix that will be prepended to resource names"
```

2021-12-28 16:57 UTC, qbart commented on examples/cloudfront/main.tf
> +output "CLOUDFRONT_domain_name" {
```suggestion
output "cloudfront_domain_name" {
```

2021-12-28 16:58 UTC, qbart commented on examples/cloudfront/main.tf
> +output "CLOUDFRONT_distribution_id" {
```suggestion
output "cloudfront_distribution_id" {
```

2021-12-28 17:01 UTC, qbart requested changes
few minors and module name could be named differently like cloudfront-invalidation

2021-12-29 20:04 UTC, mateuszwu commented
> few minors and module name could be named differently like cloudfront-invalidation

Thanks, good idea 👍

2022-01-19 10:15 UTC, qbart approved these changes

2022-01-19 10:15 UTC, merged